#!/usr/bin/perl
# login
# Mike Perron (2013)
#
# A script to create sessions.

use strict;

my $homepath = `mod_home accounts`;
my $database = "accounts.db";
my $postdata = <STDIN>;
my %postvalues;
my $okay = 0;
my $sql;
my $buffer;
my $pwhash;
my $error;
my $redir;

chomp($homepath);
chdir($homepath) or die "Can't get home.";

if(length($postdata) > 0){
	my @pairs = split(/[;&]/, $postdata);
	foreach my $pair (@pairs){
		my ($name, $value) = split(/=/, $pair);
		$value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
		$postvalues{$name} = $value; 
		chomp($postvalues{$name});
	}
}

# Rough estimate of acceptable domain names. Probably fine.
my $domain = $postvalues{domain};
if(!($domain =~ /^[a-zA-Z0-9.-]{3,}$/)){
	$domain = "";
}

my $username = $postvalues{name};
$username =~ s/\\/\\\\/g;
$username =~ s/(["'])/\\\1/g;

if(length($username) > 0){
#printf "Name fits rules.\n";
	my $pass = $postvalues{pass};
	$pass =~ s/'/'"'"'/g;

	$sql = qq/SELECT hash FROM users WHERE name="$username";/;
	chomp($pwhash = qx/echo '$username$pass' | openssl sha512/);
	$pwhash =~ s/^.*\s([a-fA-F0-9]*)$/\1/g;

	chomp($buffer = qx/sqlite3 '$database' '$sql'/);

	if((length($buffer) > 0) and ($pwhash eq $buffer)){
		$okay = 1;
		$error = "Auth Accepted";
	} else {
		# Passwords no good.
		$okay = 0;
		$error = "Bad Auth";
	}
} else {
	# Impossible user name.
	$okay = 0;
	$error = "Bad User";
}

if($okay == 1){
	$redir = $postvalues{onsuccess};
	if($redir eq ""){
		$redir = "/";
	}
} else {
	$redir = $postvalues{onfailure};
	if($redir eq ""){
		$redir = $ENV{HTTP_REFERER};
		if ($redir eq ""){
			$redir = "/";
		}
	}
}

printf "Status: 302 $error\n";
printf "Location: $redir\n";
if($okay == 1){
	chomp(my $sid = qx/create_session '$username'/);
	if(($? == 0) and (length($sid) > 0)){
		printf "Set-Cookie: knetsid=$sid; Path=/;" . ((length($domain) > 0) ? " Domain=$domain;" : "") . " Max-Age=5184000\n";
	}
}

# Probably superfluous
printf "\n";
exit 0
