#!/usr/bin/perl
# logout
# Mike Perron (2013)
#
# A script to destroy the current session.

use strict;
use DBI;

my $dbh = DBI->connect('dbi:mysql:kws', 'kraknet', '') or &fail("could not access DB");

my $cookie = $ENV{HTTP_COOKIE};
my %cookies;
if(length($cookie) > 0){
	my @pairs = split(/[;&]/, $cookie);
	foreach my $pair (@pairs){
		my ($name, $value) = split(/=/, $pair);
		$name =~ s/^\s+//;
		$value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
		chomp($cookies{$name} = $value);
	}
}

my $sid = $cookies{knetsid};
if(!($sid =~ /^[a-zA-Z]*$/)){
	print "Status: 400 Bad Session ID\n\n";
	exit 0
}

my $sql = qq/DELETE FROM sids WHERE id_session = ?;/;
my $sth = $dbh->prepare($sql);

my $logstat = "Failed";
if(length($sid) > 0){
	$sth->execute($sid);
	if(!$?){ $logstat = "Successful" }	
}

my $ref = $ENV{HTTP_REFERER};
if(length($ref) <= 0){ $ref = '/' }

printf "Status: 302 Logout $logstat\nLocation: $ref\n\n";
exit 0
