#!/usr/bin/perl
# register
# Mike Perron (2013)
#
# Create a new entry in the accounts database.

use strict;

my $homepath = `mod_home accounts`;
my $database = "accounts.db";
my $postdata = <STDIN>;
my %postvalues;
my $reg_okay = 0;
my %okay;
my $pwhash;
my $output;
my $sql;

chomp($homepath);
chdir($homepath) or die "Can't get home.";

if(length($postdata) > 0){
	my @pairs = split(/[;&]/, $postdata);
	foreach my $pair (@pairs){
		my ($name, $value) = split(/=/, $pair);
		$value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
		$postvalues{$name} = $value; 
		chomp($postvalues{$name});
	}
}

$okay{name} = 1 if($postvalues{name} =~ /^[a-z\d]{4,}+$/);

if(($postvalues{pass} eq $postvalues{repass}) and (length($postvalues{pass}) >= 6)){
	$okay{pass} = 1;

	my $pass = $postvalues{pass};
	$pass =~ s/\\/\\\\/g;
	$pass =~ s/'/\\'/g;

	chomp($pwhash = qx/echo '$postvalues{name}$pass' | openssl sha512/);
}

if(($okay{name} == 1) and ($okay{pass} == 1)){
	$reg_okay = 1;

	$sql = qq/SELECT name FROM users WHERE name="$postvalues{name}";/;
	chomp($output = qx/sqlite3 '$database' '$sql'/);

	if($output eq ""){
		$sql = qq/INSERT INTO users(name, hash, pretty) values("$postvalues{name}", "$pwhash", "$postvalues{name}");/;
		chomp($output = qx/sqlite3 '$database' '$sql'/);
	} else {
		$reg_okay = 0;
	}
}

my $redir;
if($reg_okay == 1){
	printf "Status: 302 Registration OK\n";
	$redir = $postvalues{onsuccess};
	if($redir eq ""){
		$redir = "/";
	}

	# Registration worked, so there's no reason create_session should fail...right?
	printf "Set-Cookie: knetsid=" . qx/create_session '$postvalues{name}'/ . "; Path=/; Max-Age=5184000\n";
	printf "Location: $redir\n\n";
} else {
	printf "Status: 302 Registration Failed\n";
	$redir = $postvalues{onfailure};
	if($redir eq ""){
		$redir = $ENV{HTTP_REFERER};
		if ($redir eq ""){
			$redir = "/";
		}
	}
	printf "Location: $redir\n\n";
}

exit 0
