#!/usr/bin/perl
# register
# Mike Perron (2013)
#
# Create a new entry in the accounts database.

use strict;
use DBI;

my $dbh = DBI->connect('dbi:mysql:kws', 'kraknet', '') or &fail("could not access DB");

my $postdata = <STDIN>;
my %postvalues;
my $reg_okay = 0;
my %okay;
my $pwhash;

my $error = "";

if(length($postdata) > 0){
	my @pairs = split(/[;&]/, $postdata);
	foreach my $pair (@pairs){
		my ($name, $value) = split(/=/, $pair);
		$value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
		$postvalues{$name} = $value; 
		chomp($postvalues{$name});
	}
}

# Rough estimate of acceptable domain names. Probably fine.
my $domain = $postvalues{domain};
if(!($domain =~ /^[a-zA-Z0-9.-]{3,}$/)){
	$domain = "";
}

if($postvalues{name} =~ /^[A-Za-z\d_\-]{4,128}+$/){
	$postvalues{name} = lc($postvalues{name});
	$okay{name} = 1
} else {
	$error = "Invalid username.";
}

if(length($postvalues{pass}) < 6){
	$error = "Password must be at least six characters.";
} elsif($postvalues{pass} ne $postvalues{repass}){
	$error = "The two passwords must match.";
} else {
	$okay{pass} = 1;

	my $pass = $postvalues{pass};
	$pass =~ s/'/'"'"'/g;

	chomp($pwhash = qx/echo '$postvalues{name}$pass' | openssl sha512/);
	$pwhash =~ s/^.*\s([a-fA-F0-9]*)$/\1/g;
}

if(($okay{name} == 1) and ($okay{pass} == 1)){
	$reg_okay = 1;

	my $sql = qq/SELECT name FROM users WHERE name = ?;/;
	my $sth = $dbh->prepare($sql);
	$sth->execute($postvalues{name});

	if(!$sth->fetchrow_array()){
		$sql = qq/INSERT INTO users(name, hash, pretty) values(?, ?, ?);/;
		$sth = $dbh->prepare($sql);
		$sth->execute($postvalues{name}, $pwhash, $postvalues{name});
	} else {
		$reg_okay = 0;
		$error = "That username is already taken.";
	}
}

my $redir;

if($reg_okay == 1){
	print "Status: 200 Registration Success\n";

	$redir = $postvalues{onsuccess};
	if($redir eq ""){
		$redir = "/";
	}

	# Registration worked, so there's no reason create_session should fail...right?
	print "Set-Cookie: knetsid=" . qx/create_session '$postvalues{name}'/ . "; Path=/;" . ((length($domain) > 0) ? " Domain=$domain;" : "") . " Max-Age=5184000\n";
} else {
	print "Status: 200 Registration Failed\n";

	$redir = $postvalues{onfailure};
	if($redir eq ""){
		$redir = $ENV{HTTP_REFERER};
		if ($redir eq ""){
			$redir = "/";
		}
	}
}

print qq{Content-Type: application/json; charset=utf-8

{"okay":$reg_okay,"redir":"$redir","error":"$error"}
};
exit 0
