#!/bin/bash
# Create a clean accounts database.

cat << EOF
WARNING! Before proceeding, please make sure that a user "kraknet" has
all permissions to kws.* in MySQL, and that your MySQL server is
running.

To configure as such, log into your MySQL with this command:
	mysql -u root -p

Create the database:
	create database kws;

And grant permissions:
	grant all on kws.* to 'kraknet'@'localhost';


Press [Ctrl-C] to cancel or [ENTER] to continue.
EOF
read meow

database="kws"
schema="
DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id_user INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(512),
	hash VARCHAR(512),
	pretty VARCHAR(512),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS sids;
CREATE TABLE sids (
	id_session VARCHAR(128) NOT NULL PRIMARY KEY,
	id_user INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);"

if mysql -u kraknet "$database" <<< "$schema"; then
	echo "Database created."
else
	echo "WARNING: Error encountered."
	exit 1
fi
